### ISSUE TITLE
Use Migration mechanism to create the tables

### ISSUE THREAD

**Issue by bwaidelich** [neos/Neos.EventStore.DatabaseStorageAdapter#6]
Creating the ES tables via `flow eventstore:createschema` still fails for me (`Unknown column type "flow_json_array" requested.`). Besides every `flow doctrine:migrationgenerate` wants to delete the ES tables).

So I'd suggest to replace the `EventStoreSchema` by a dummy entity that could look sth like this:
```php
/**
 * @Flow\Entity(readOnly=true)
 * @internal This class is only used as schema provider for the required db table
 */
class EventStoreSchema
{

    /**
     * @ORM\Column(type="text")
     * @var string
     */
    protected $streamName;

    // ...
}
```
and to create a standard doctrine migration for that

**Comment by dfeyer** [comment]
My issue with using the current migration is that you have no option to have the event store in an other database (understand by using an other connection. In our case the store will be on a dedicated database (performance, backup, modular infrastructure, ...). If we move to the migration mechanism we are bound the the Flow database connection. 

And feel quiet awkard to annotate Entity something that is not an Entity

**Comment by bwaidelich** [comment]
Good point, I agree.. Some ideas though:
* there's a new Flow setting that allows to blacklist tables from migrationgenerate. I can't look it up right now but we should be able to use that here
* Can we use the Flow EntityManager (or at least the Flow connection settings) by default?
* Maybe too early but at some point we could move the  CLI command to the generic EventStore package (maybe call it sth like `setup` or `validate`) and have some method in the adapter interface. We'll probably need sth like this for most implementations

**Comment by robertlemke** [comment]
If it's not too much work, it would be great to find a way using the migration mechanism but in a separate database. I mean, ideally you could define additional database configurations in Flow and `doctrine:migrate`, `doctrine:migrationgenerate` would accept a parameter for choosing these alternative configurations. 

As for the `Entity` annotation: we have a similar problem with the Read Models. It's a little change in Flow (Reflection Service, where the Class Schema is built) which would allow us to build class schemata for custom annotations. But for this specific case it is probably easier to use the blacklist approach @bwaidelich mentioned.

In general: if it's possible to re-use well-known deployment or migration mechanisms, that would be great and worth some extra effort.

**Comment by bwaidelich** [comment]
I agree that it would be nice to make this work out of the box but still be extensible.
One thing that should be possible from the start (IMO) is a different configuration per Bounded Context / Package.
E.g. I want one event stream table per BC or even a completely different storage backend for one. I think that's pretty important especially if we start to use the EventStore for parts of the core (like we plan with the Content Repository)

**Comment by bwaidelich** [comment]
This issue was moved to neos/Neos.Cqrs#42
